### ISSUE TITLE
Request: light variant of Powerline theme

### ISSUE THREAD

**Issue by Ketsuban** [Malabarba/smart-mode-line#150] opened 2015-09-06 02:58 UTC
I don't want to use a dark theme (I'm using the Emacs default light theme, as it happens) but I do want Powerline-style segment borders. Could you provide some Lisp forms to change the colours to something more fitting, if possible, or a separate tweaked version of the powerline theme?

**Comment by Malabarba** [comment] 2015-09-06 09:55
Yes, you're not the first to request that, and I'd love to accept a PR on this.
The powerline-theme file should be very easy to understand, and all you have to do is make a copy of that file and change the colors defined there.
Would you like ot give it a try?

**Comment by Malabarba** [comment] 2015-10-19 20:21
Closing this as duplicate of #103. A PR on this would still be very welcome.

**Closed by Malabarba** 2015-10-19 20:21 UTC
