### ISSUE TITLE
Unable to run Powerline theme

### ISSUE THREAD

**Issue by WorldsEndless** [Malabarba/smart-mode-line#122] opened 2015-03-14 14:51 UTC
As of a few minutes ago when I ran a package update, I can no longer load the powerline theme. 
    Compiling file ~/.emacs.d/elpa/smart-mode-line-powerline-theme-20141229.1046/smart-mode-line-powerline-theme-autoloads.el at Sat Mar 14 10:45:44 2015
    Entering directory `~/.emacs.d/elpa/smart-mode-line-powerline-theme-20141229.1046/'

    Compiling file ~/.emacs.d/elpa/smart-mode-line-powerline-theme-20141229.1046/smart-mode-line-powerline-theme-pkg.el at Sat Mar 14 10:45:44 2015

    Compiling file ~/.emacs.d/elpa/smart-mode-line-powerline-theme-20141229.1046/smart-mode-line-powerline-theme.el at Sat Mar 14 10:45:44 2015
    smart-mode-line-powerline-theme.el:36:1:Error: Symbol's value as variable is void: left

I'm running GNU Emacs 25.0.50.6 (x86_64-unknown-linux-gnu, GTK+ Version 3.10.9) of 2015-02-10 on localhost.localdomain
It was working fine until an until an emacs reboot after package downloading a few minutes ago (last reboot before that: yesterday morning)

**Comment by Bruce-Connor** [comment] 2015-03-14 15:47
Thanks for reporting.
That's a little strange. The theme hasn't been updated in a while. 
Could you try reinstalling the package?

**Comment by WorldsEndless** [comment] 2015-03-14 16:45
Yeah, I've tried that. As far as I can tell by following the trace, it seems to be related to some change in powerline.el. After evaluating powerline.el itself I was then able to apply the powerline theme without complaint.

**Comment by Bruce-Connor** [comment] 2015-03-14 18:03
Ok. That could be the cause. 
Next chance I get I'll update powerline here and try to reproduce it.

**Comment by acowley** [comment] 2015-03-18 19:12
I'm seeing this too on 24.4.

**Comment by WorldsEndless** [comment] 2015-03-18 19:24
The problem returned after another update to powerline (not sml-powerline). At length I got around it by uninstalling and reinstalling sml.

**Comment by acowley** [comment] 2015-03-18 19:48
Okay, I deleted and re-installed things several times. The last time around, I deleted powerline, sml, and sml-powerline, and it seems to have cleared up. Thanks for the suggestion @WorldsEndless.

**Comment by Bruce-Connor** [comment] 2015-03-18 20:41
That's good to know. powerline probably made some backwards-incompatible change in some macro, so sml-powerline needed to be recompiled.

I might release an empty version bump to sml-powerline soon just so that it gets reinstalled when people upgrade.

**Comment by Malabarba** [comment] 2015-04-02 17:10
Ok, I've closed this since it seems to be resolved with a reinstall. But do let me know if you run into it again.

**Closed** 2015-04-02 17:09 UTC
